Created `shape` , `dimensions`, and `volume` methods on the `Core` class (#49)
* Started on the shape method

* Finished the shape method

* Started on the dimensions function

* Starting adding a unit enum

* Added the ability to specify dimensions. Commiting to save this code

* Finished the dimensions method

* Finished the volume function

* Updated core declarations to use tuples

* Addressed some comments

* Removed the min_density and max_density arguments on the volume function

* Updated the docstring

* Updated version number

* retriggering the github action

diff --git a/.github/workflows/verify_version_number.yaml b/.github/workflows/verify_version_number.yaml
--- a/.github/workflows/verify_version_number.yaml
+++ b/.github/workflows/verify_version_number.yaml
@@ -2,38 +2,37 @@ name: "Verify Version Number"
 
 on:
   pull_request:
-    branches: [ "main" ]
+    branches: ["main"]
 
 permissions:
   contents: read
 
 jobs:
   verify_version_number:
-
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout Main Branch
-      uses: actions/checkout@v4
-      with:
-        ref: main
-    - name: Parse Main Branch Version
-      run: echo MAIN_VER=$(grep version pyproject.toml | sed -e 's/version = "\(.*\)"/\1/') >> $GITHUB_ENV
-    - name: Checkout Feature Branch
-      uses: actions/checkout@v4
-    - name: Parse Feature Branch Version
-      run: echo FEATURE_VER=$(grep version pyproject.toml | sed -e 's/version = "\(.*\)"/\1/') >> $GITHUB_ENV
-    - name: Check For Version Increment
-      run: |
-        if [ $MAIN_VER == $FEATURE_VER ]
-        then
-          echo "::error::Feature branch version $FEATURE_VER must be greater than main branch version $MAIN_VER. Update the package version in pyproject.toml to fix this error."
-          exit 1
-        fi
-        if echo -e "$MAIN_VER\n$FEATURE_VER" | sort --version-sort --check
-        then
-          :
-        else
-          echo "::error::Feature branch version $FEATURE_VER must be greater than main branch version $MAIN_VER. Update the package version in pyproject.toml to fix this error."
-          exit 1
-        fi
+      - name: Checkout Main Branch
+        uses: actions/checkout@v4
+        with:
+          ref: main
+      - name: Parse Main Branch Version
+        run: echo MAIN_VER=$(grep version pyproject.toml | sed -e 's/version = "\(.*\)"/\1/') >> $GITHUB_ENV
+      - name: Checkout Feature Branch
+        uses: actions/checkout@v4
+      - name: Parse Feature Branch Version
+        run: echo FEATURE_VER=$(grep version pyproject.toml | sed -e 's/version = "\(.*\)"/\1/') >> $GITHUB_ENV
+      - name: Check For Version Increment
+        run: |
+          if [ $MAIN_VER == $FEATURE_VER ]
+          then
+            echo "::error::Feature branch version $FEATURE_VER must be greater than main branch version $MAIN_VER. Update the package version in pyproject.toml to fix this error."
+            exit 1
+          fi
+          if echo -e "$MAIN_VER\n$FEATURE_VER" | sort --version-sort --check
+          then
+            :
+          else
+            echo "::error::Feature branch version $FEATURE_VER must be greater than main branch version $MAIN_VER. Update the package version in pyproject.toml to fix this error."
+            exit 1
+          fi
